backend/controllers/AnggotaController.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\Anggota;
use backend\models\AnggotaSearch;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\data\Pagination;
use yii\web\UploadedFile;
use yii\db\Query;

/**
 * AnggotaController implements the CRUD actions for Anggota model.
 */
class AnggotaController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['error', 'index', 'view'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['create', 'update', 'delete'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Anggota models.
     * @return mixed
     */
    public function actionIndex($angkatan=1)
    {
        // $query = Anggota::find()->where(['angkatan' => 2009]);
        // $countQuery = clone $query;
        // $pages = new Pagination(['totalCount' => $countQuery->count()]);
        // $models = $query->offset($pages->offset)
        //     ->limit($pages->limit)
        //     ->all();

        $myCondition = Yii::$app->user->isGuest;

        // $query = new Query;             
        // $query->select('angkatan')->from(TabAccount::anggota())->distinct();

        // $command = $query->createCommand();
        // $datas = $command->queryAll();

        // foreach ($datas as $data){

        // }

        $query = Yii::$app->db->CreateCommand('SELECT DISTINCT angkatan FROM anggota ORDER BY angkatan ASC')->queryAll();

        // $query = mysql_query("SELECT * FROM anggota WHERE angkatan=$angkatan");
        // while($row = mysql_fetch_array($query))
        // {

        // }

        $searchModel = new AnggotaSearch();
        $searchModel->angkatan = $angkatan;
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'myCondition' => $myCondition,
            'query' => $query,
            // 'models' => $models,
            // 'pages' => $pages,
        ]);
    }

    /**
     * Displays a single Anggota model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Anggota model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Anggota();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Anggota model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        // $model = $this->findModel($id);

        // if ($model->load(Yii::$app->request->post()) && $model->save()) {
        //     return $this->redirect(['view', 'id' => $model->id]);
        // }

        // $model->gambar = Yii::$app->basePath . '/web/images/members/' . $model->gambar;
        // return $this->render('update', [
        //     'model' => $model,
        // ]);


        $model = $this->findModel($id);
        $oldImage = $model->gambar;
        if ($model->load(Yii::$app->request->post()))
        {
            $image = UploadedFile::getInstance($model, 'gambar');
            if(!isset($image)){
                $model->gambar = $oldImage;
            }
            if($model->save())
            {
                if(isset($image)){
                    $image->saveAs(Yii::$app->basePath . '/web/images/members/' . $model->gambar);   
                }
            }
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Anggota model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Anggota model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Anggota the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Anggota::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

backend/controllers/EventController.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\Event;
use backend\models\EventSearch;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use yii\data\ActiveDataProvider;
/**
 * EventController implements the CRUD actions for Event model.
 */
class EventController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['error', 'index', 'view'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['create', 'update', 'delete'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Event models.
     * @return mixed
     */
    public function actionIndex()
    {
        $queryString = 'SELECT * FROM EVENT DESC';
        $dataProvider = new ActiveDataProvider([
            'query' => Event::find()->orderBy('id DESC'),
            'pagination' => [
                'pageSize' =>20,
            ],
        ]);

        $this->view->title = 'Event';
        return $this->render('index', ['dataProvider' => $dataProvider]);
    }

    /**
     * Lists all Event models.
     * @return mixed
     */
    public function actionIndex2()
    {
        $searchModel = new EventSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        $myCondition = Yii::$app->user->isGuest;

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'myCondition' => $myCondition,
        ]);
    }

    /**
     * Displays a single Event model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Event model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Event();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            // $image_1 = UploadedFile::getInstance($model, 'gambar_1');
            // $model->gambar_1= $image_1->name;
            // $path_1 = Yii::$app->basePath . '/web/images/events/' . $model->gambar_1;
            // if($model->save())
            // {
            //     $image_1->saveAs($path_1);
            //     // Yii::$app->getSession()->setFlash('error', 'User type inserted successfully');
            // }
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Event model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        // $model = $this->findModel($id);

        // if ($model->load(Yii::$app->request->post()) && $model->save()) {
        //     // $image_1 = UploadedFile::getInstance($model, 'gambar_1');
        //     // $model->gambar_1= $image_1->name;
        //     // $path_1 = Yii::$app->basePath . '/web/images/events/' . $model->gambar_1;
        //     // if($model->save())
        //     // {
        //     //     $image_1->saveAs($path_1);
        //     //     // Yii::$app->getSession()->setFlash('error', 'User type inserted successfully');
        //     // }
        //     return $this->redirect(['view', 'id' => $model->id]);
        // }

        // return $this->render('update', [
        //     'model' => $model,
        // ]);


        $model = $this->findModel($id);
        $oldImage_1 = $model->gambar_1;
        $oldImage_2 = $model->gambar_2;
        $oldImage_3 = $model->gambar_3;
        $oldImage_4 = $model->gambar_4;
        $oldImage_5 = $model->gambar_5;
        if ($model->load(Yii::$app->request->post()))
        {
            $image_1 = UploadedFile::getInstance($model, 'gambar_1');
            $image_2 = UploadedFile::getInstance($model, 'gambar_2');
            $image_3 = UploadedFile::getInstance($model, 'gambar_3');
            $image_4 = UploadedFile::getInstance($model, 'gambar_4');
            $image_5 = UploadedFile::getInstance($model, 'gambar_5');
            if(!isset($image_1)){
                $model->gambar_1 = $oldImage_1;
            }
            if(!isset($image_2)){
                $model->gambar_2 = $oldImage_2;
            }
            if(!isset($image_3)){
                $model->gambar_3 = $oldImage_3;
            }
            if(!isset($image_4)){
                $model->gambar_4 = $oldImage_4;
            }
            if(!isset($image_5)){
                $model->gambar_5 = $oldImage_5;
            }
            if($model->save())
            {
                if(isset($image_1)){
                    $image_1->saveAs(Yii::$app->basePath . '/web/images/members/' . $model->gambar_1);   
                }
                if(isset($image_2)){
                    $image_2->saveAs(Yii::$app->basePath . '/web/images/members/' . $model->gambar_2);   
                }
                if(isset($image_3)){
                    $image_3->saveAs(Yii::$app->basePath . '/web/images/members/' . $model->gambar_3);   
                }
                if(isset($image_4)){
                    $image_4->saveAs(Yii::$app->basePath . '/web/images/members/' . $model->gambar_4);   
                }
                if(isset($image_5)){
                    $image_5->saveAs(Yii::$app->basePath . '/web/images/members/' . $model->gambar_5);   
                }
            }
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Event model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Event model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Event the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Event::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use backend\models\ContactForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error', 'index', 'contact'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending your message.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }
}

backend/views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
?>
<div class="container3">
    <div class="site-contact">
        <div class="sejarah-img">
            <?php echo Html::img(Yii::$app->request->BaseUrl.'/images/contact.png', ['class'=>'imgSejarah']) ?>
        </div>

        <div class="one">
            <h1><?= Html::encode($this->title) ?></h1>

            <p>
                If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.
            </p>
            <p>
                SMA Negeri 1 Medan
            </p>
            <p>
                Jalan Teuku Cik Ditiro No.1, Madras Hulu, Medan Polonia, Madras Hulu, Medan Polonia, Kota Medan, Sumatera Utara 20152
            </p>
            <p>
                Telp. (061) 4511765
            </p>
            <p>
                HP. 082165100594
            </p>
            <p>
                Email. solagratia.choir@gmail.com
            </p>
            <br>
            <div class="row">
                <div class="col-lg-5">
                    <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>
        
                        <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>
        
                        <?= $form->field($model, 'email') ?>
        
                        <?= $form->field($model, 'subject') ?>
        
                        <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>
        
                        <?php /* $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                            'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                        ]) */?>
        
                        <div class="form-group">
                            <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                        </div>
        
                    <?php ActiveForm::end(); ?>
                </div>
            </div>
        </div>
        <div class="two">
                <?php
                        $rows = (new \yii\db\Query())
                        ->select(['id','nama', 'tanggal_mulai','tanggal_selesai','lokasi', 'deskripsi', 'gambar_1','gambar_2','gambar_3','gambar_4','gambar_5'])
                        ->from('event')
                        ->limit(3)
                        ->orderBy(['id'=>SORT_DESC])
                        ->all();
                        foreach ($rows as $row){
                            echo "<div class='grid-sidebar'>";
                            echo Html::img(Yii::$app->request->BaseUrl.'/images/' . $row['gambar_1'], ['class'=>'foto-icon']);
                            echo Html::a($row['nama'], ['event/view','id'=>$row['id']], ['title' => 'View']);
                            echo "</div>";
                        }
                    ?>
        </div>
    </div>
</div>

backend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<br><br><br>
<div class="container3">
    <div class="site-error">
        <div class="sejarah-img">
                <?php echo Html::img(Yii::$app->request->BaseUrl.'/images/' . $model->gambar_1, ['class'=>'imgSejarah']) ?>
        </div>

    
        <h1><?= Html::encode($this->title) ?></h1>
    
        <div class="alert alert-danger">
            <?= nl2br(Html::encode($message)) ?>
        </div>
    
        <p>
            The above error occurred while the Web server was processing your request.
        </p>
        <p>
            Please contact us if you think this is a server error. Thank you.
        </p>
    
    </div>
</div>

backend/views/site/index.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;
$this->title = 'My Yii Application';
?>
<div class="container3">
<iframe width="100%" height="610" src="https://www.youtube.com/embed/Yfe2osnXMnw" frameborder="0" gesture="media" allow="encrypted-media" allowfullscreen></iframe></div>
            <div class="col-lg-4" style="text-align:justify;text-justify:inter-word;">
                <h2>About Sola Gratia</h2>

                <p>Dalam perkembangannya sampai saat ini, Paduan Suara Sola Gratia yang telah mencapai usia 20 tahun dan melahirkan 22 angkatan, telah banyak mengikuti dan memenangkan kompetisi paduan suara yang bertaraf nasional dan internasional dan juga telah menyelenggarakan beberapa konser sebagai wujud pelayanan memuji nama Tuhan Yesus.
                <p><?php echo Html::a('See more &raquo;', ['sejarah/index'], ['class' => 'btn btn-default'])?></p>
            </div>
            <div class="col-lg-4" style="text-align:justify;text-justify:inter-word;">
                <h2>Event Sola Gratia</h2>

                <p>Paduan Suara Sola Gratia telah mengadakan 3 kali kunjungan daerah, 8 kali konser dan mengikuti berbagai kompetis baik dari tingkat daerah, nasional dan internasional. Paduan Suara Sola Gratia juga memenuhi undangan dari berbagai instasi dan golongan. Yang paling utama adalah Paduan Suara Sola Gratia melakukan kunjungan gereja secara berkala.</p>

                <p><?php echo Html::a('See more &raquo;', ['event/index'], ['class' => 'btn btn-default'])?></p>
            </div>
            <div class="col-lg-4" style="text-align:justify;text-justify:inter-word;">
                <h2>Anggota Sola Gratia</h2>

                <p>Hingga Saat ini Paduan Suara Sola Gratia Beranggotakan lebih dari 400 orang yang melingkupi siswa SMA dan alumni. Solidaritas dan kekeluargaan antar anggota masih terjalin baik hingga saat ini. Hal ini terbukti dengan dukungan dari alumnni dalam setiap kegiatan Paduan Suara Sola Gratia.</p>

                <p><?php echo Html::a('See more &raquo;', ['anggota/index'], ['class' => 'btn btn-default'])?></p>
            </div>
</div>

backend/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
?>
<div class="container3">
    <div class="site-login">
        <div class="sejarah-img">
                <?php echo Html::img(Yii::$app->request->BaseUrl.'/images/histories/test.jpg' , ['class'=>'imgSejarah']) ?>
        </div>
  
    
        <h1><?= Html::encode($this->title) ?></h1>
    
        <p>Please fill out the following fields to login:</p>
    
        <div class="row">
            <div class="col-lg-5">
                <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>
    
                    <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>
    
                    <?= $form->field($model, 'password')->passwordInput() ?>
    
                    <?= $form->field($model, 'rememberMe')->checkbox() ?>
    
                    <div class="form-group">
                        <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                    </div>
    
                <?php ActiveForm::end(); ?>
            </div>
        </div>
    </div>
</div>