backend/models/Pembina.php
<?php

namespace app\models;

use Yii;
use yii\web\UploadedFile;
use yii\helpers\Html;

/**
 * This is the model class for table "pembina".
 *
 * @property int $id
 * @property string $nama
 * @property string $tempat_lahir
 * @property string $tanggal_lahir
 * @property string $periode
 * @property string $deskripsi
 * @property string $gambar
 * @property string $alamat
 * @property string $no_handphone
 */
class Pembina extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'pembina';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['tanggal_lahir'], 'safe'],
            [['nama', 'tempat_lahir', 'periode'], 'string', 'max' => 100],
            [['deskripsi', 'gambar', 'alamat', 'no_handphone'], 'string'],
            [['gambar'], 'file', 'skipOnEmpty' => true, 'extensions'=>'jpg, gif, png, jpeg'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nama' => 'Nama',
            'tempat_lahir' => 'Tempat Lahir',
            'tanggal_lahir' => 'Tanggal Lahir',
            'periode' => 'Periode',
            'deskripsi' => 'Deskripsi',
            'gambar' => 'Gambar',
            'alamat' => 'Alamat',
            'no_handphone' => 'No Handphone',
        ];
    }

    public function afterSave($insert, $changedAttributes)
    {
        if(isset($this->gambar)){
            $this->gambar=UploadedFile::getInstance($this,'gambar');
            if(is_object($this->gambar)){
                $path=Yii::$app->basePath . '/web/images/pembinas/';  //set directory path to save image
                $this->gambar->saveAs($path.$this->gambar);   //saving img in folder
                $this->gambar = 'pembinas/'.$this->gambar;    //appending id to image name            
                \Yii::$app->db->createCommand()
                      ->update('pembina', ['gambar' => $this->gambar], 'id = "'.$this->id.'"')
                      ->execute(); //manually update image name to db
            }
        }
    }
}

backend/controllers/EventController.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\Event;
use backend\models\EventSearch;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use yii\data\ActiveDataProvider;
/**
 * EventController implements the CRUD actions for Event model.
 */
class EventController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['error', 'index', 'view'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['create', 'update', 'delete'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Event models.
     * @return mixed
     */
    public function actionIndex()
    {
        $queryString = 'SELECT * FROM EVENT DESC';
        $dataProvider = new ActiveDataProvider([
            'query' => Event::find()->orderBy('id DESC'),
            'pagination' => [
                'pageSize' =>20,
            ],
        ]);

        $this->view->title = 'Event';
        return $this->render('index', ['dataProvider' => $dataProvider]);
    }

    /**
     * Lists all Event models.
     * @return mixed
     */
    public function actionIndex2()
    {
        $searchModel = new EventSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        $myCondition = Yii::$app->user->isGuest;

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'myCondition' => $myCondition,
        ]);
    }

    /**
     * Displays a single Event model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Event model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Event();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            // $image_1 = UploadedFile::getInstance($model, 'gambar_1');
            // $model->gambar_1= $image_1->name;
            // $path_1 = Yii::$app->basePath . '/web/images/events/' . $model->gambar_1;
            // if($model->save())
            // {
            //     $image_1->saveAs($path_1);
            //     // Yii::$app->getSession()->setFlash('error', 'User type inserted successfully');
            // }
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Event model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        // $model = $this->findModel($id);

        // if ($model->load(Yii::$app->request->post()) && $model->save()) {
        //     // $image_1 = UploadedFile::getInstance($model, 'gambar_1');
        //     // $model->gambar_1= $image_1->name;
        //     // $path_1 = Yii::$app->basePath . '/web/images/events/' . $model->gambar_1;
        //     // if($model->save())
        //     // {
        //     //     $image_1->saveAs($path_1);
        //     //     // Yii::$app->getSession()->setFlash('error', 'User type inserted successfully');
        //     // }
        //     return $this->redirect(['view', 'id' => $model->id]);
        // }

        // return $this->render('update', [
        //     'model' => $model,
        // ]);


        $model = $this->findModel($id);
        $oldImage_1 = $model->gambar_1;
        $oldImage_2 = $model->gambar_2;
        $oldImage_3 = $model->gambar_3;
        $oldImage_4 = $model->gambar_4;
        $oldImage_5 = $model->gambar_5;
        if ($model->load(Yii::$app->request->post()))
        {
            $image_1 = UploadedFile::getInstance($model, 'gambar_1');
            $image_2 = UploadedFile::getInstance($model, 'gambar_2');
            $image_3 = UploadedFile::getInstance($model, 'gambar_3');
            $image_4 = UploadedFile::getInstance($model, 'gambar_4');
            $image_5 = UploadedFile::getInstance($model, 'gambar_5');
            if(!isset($image_1)){
                $model->gambar_1 = $oldImage_1;
            }
            if(!isset($image_2)){
                $model->gambar_2 = $oldImage_2;
            }
            if(!isset($image_3)){
                $model->gambar_3 = $oldImage_3;
            }
            if(!isset($image_4)){
                $model->gambar_4 = $oldImage_4;
            }
            if(!isset($image_5)){
                $model->gambar_5 = $oldImage_5;
            }
            if($model->save())
            {
                if(isset($image_1)){
                    $image_1->saveAs(Yii::$app->basePath . '/web/images/members/' . $model->gambar_1);   
                }
                if(isset($image_2)){
                    $image_2->saveAs(Yii::$app->basePath . '/web/images/members/' . $model->gambar_2);   
                }
                if(isset($image_3)){
                    $image_3->saveAs(Yii::$app->basePath . '/web/images/members/' . $model->gambar_3);   
                }
                if(isset($image_4)){
                    $image_4->saveAs(Yii::$app->basePath . '/web/images/members/' . $model->gambar_4);   
                }
                if(isset($image_5)){
                    $image_5->saveAs(Yii::$app->basePath . '/web/images/members/' . $model->gambar_5);   
                }
            }
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Event model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Event model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Event the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Event::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

backend/controllers/PembinaController.php
<?php

namespace backend\controllers;

use Yii;
use app\models\Pembina;
use app\models\PembinaSearch;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * PembinaController implements the CRUD actions for Pembina model.
 */
class PembinaController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['error', 'index', 'view'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['create', 'update', 'delete'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Pembina models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PembinaSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        $myCondition = Yii::$app->user->isGuest;

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'myCondition' => $myCondition,
        ]);
    }

    /**
     * Displays a single Pembina model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Pembina model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Pembina();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Pembina model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $oldImage = $model->gambar;
        if ($model->load(Yii::$app->request->post()))
        {
            $image = UploadedFile::getInstance($model, 'gambar');
            if(!isset($image)){
                $model->gambar = $oldImage;
            }
            if($model->save())
            {
                if(isset($image)){
                    $image->saveAs(Yii::$app->basePath . '/web/images/members/' . $model->gambar);   
                }
            }
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Pembina model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Pembina model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Pembina the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Pembina::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

backend/views/pembina/_ad.php
<div class="list-item col-sm-12 ad-item">
    <p>AD</p>
    <img src="http://placehold.it/468x60" alt="">
</div>

backend/views/pembina/_form.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use kartik\file\FileInput;
use yii\jui\DatePicker;

/* @var $this yii\web\View */
/* @var $model app\models\Pembina */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="pembina-form">

    <?php $form = ActiveForm::begin([
        'layout' => 'horizontal',
        'options'=>['enctype'=>'multipart/form-data'],
        'fieldConfig' => [
            'template' => "{label}\n{beginWrapper}\n{input}\n{hint}\n{error}\n{endWrapper}",
            'horizontalCssClasses' => [
                'label' => 'col-sm-2',
                'offset' => 'col-sm-offset-4',
                'wrapper' => 'col-sm-4',
                'error' => '',
                'hint' => '',
            ],
        ],
    ]); ?>

    <?= $form->field($model, 'nama')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'tempat_lahir')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'tanggal_lahir')->widget(DatePicker::className(),[
            'clientOptions' => [
                'defaultDate' => '2014-01-01',
                // 'yearRange' => 'c-50:c-20',
                'changeMonth'=> true,
                'changeYear'=> true,
            ],
            'options'=>['style'=>'width:250px;', 'class'=>'form-control'],
            'dateFormat' => 'yyyy-MM-dd',
        ]) ?>

    <?= $form->field($model, 'alamat')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'no_handphone')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'periode')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'deskripsi')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'gambar')->widget(FileInput::classname(), [
        'options' => ['accept' => 'image/*', 'multiple' => false],
        'pluginOptions' => [
            'showUpload' => false,
            'browseIcon' => '<i class="glyphicon glyphicon-camera"/> ',
        ]
    ]) ?>
    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/pembina/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\PembinaSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="pembina-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'nama') ?>

    <?= $form->field($model, 'tempat_lahir') ?>

    <?= $form->field($model, 'tanggal_lahir') ?>

    <?= $form->field($model, 'periode') ?>

    <?php // echo $form->field($model, 'deskripsi') ?>

    <?php // echo $form->field($model, 'gambar') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/pembina/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Pembina */

$this->title = 'Create Pembina';
$this->params['breadcrumbs'][] = ['label' => 'Pembina', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="pembina-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/pembina/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\ListView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\PembinaSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Pembina';
?>
<div class="container3">
    <div class="pembina-index">
    
        <div class="sejarah-img">
            <?php echo Html::img(Yii::$app->request->BaseUrl.'/images/pembina.jpg', ['class'=>'imgSejarah']) ?>
        </div>

        <h1>Pembina Sola Gratia</h1>
        <?php // echo $this->render('_search', ['model' => $searchModel]); ?>
    
        <p>
            <?php if (Yii::$app->user->isGuest == false) {
                    echo Html::a('Create Pembina', ['create'], ['class' => 'btn btn-success']);
                }
            ?>
        </p>
        <div class="one">
            <div class="sejarah-isi">
            <?php 
                foreach ($dataProvider->models as $model){
                    echo Html::img(Yii::$app->request->BaseUrl.'/images/' . $model->gambar, ['class'=>'foto-profil']);
                    echo Html::a($model->nama, ['pembina/view','id'=>$model->id], ['title' => 'View','class'=>'keterangan-profil']);
                    echo "<br><hr>";
                }
            ?>
            </div>
        </div>
        <div class="two">
                <?php
                    $rows = (new \yii\db\Query())
                    ->select(['id','nama', 'tanggal_mulai','tanggal_selesai','lokasi', 'deskripsi', 'gambar_1','gambar_2','gambar_3','gambar_4','gambar_5'])
                    ->from('event')
                    ->limit(3)
                    ->orderBy(['id'=>SORT_DESC])
                    ->all();
                    foreach ($rows as $row){
                        echo "<div class='grid-sidebar'>";
                        echo Html::img(Yii::$app->request->BaseUrl.'/images/' . $row['gambar_1'], ['class'=>'foto-icon']);
                        echo Html::a($row['nama'], ['event/view','id'=>$row['id']], ['title' => 'View']);
                        echo "</div>";
                        
                    }
                ?>
        </div>
    </div>
</div>

backend/views/pembina/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Pembina */

$this->title = 'Update Pembina';
$this->params['breadcrumbs'][] = ['label' => 'Pembina', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="pembina-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/pembina/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Pembina */

$this->title = $model->id;
?>
<div class="container3">
    <div class="pembina-view">
            <div class="sejarah-img">
                <?php echo Html::img(Yii::$app->request->BaseUrl.'/images/pembina.jpg', ['class'=>'imgSejarah']) ?>
            </div>
            <p>
                <?php if (Yii::$app->user->isGuest == false) {
                        echo Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']);
                    }
                ?>
                <?php if (Yii::$app->user->isGuest == false) {
                        echo Html::a('Delete', ['delete', 'id' => $model->id], [
                            'class' => 'btn btn-danger',
                            'data' => [
                                'confirm' => 'Are you sure you want to delete this item?',
                                'method' => 'post',
                            ],
                        ]);
                    }
                ?>
            </p>
            <br>
            <div class="one">

            <?php echo Html::img(Yii::$app->request->BaseUrl.'/images/' . $model->gambar, ['class'=>'foto-profil-detail']) ?>
    
            
            <h1><?= Html::encode($model->nama) ?></h1>
            <div class="sejarah-isi">
            </div>
            
            
            <table class="detail-profil">
              <tr>
              </tr>
              <tr>
                <td colspan="2"><div class="justify"><?php echo $model->deskripsi; ?></div><br></td>
              </tr>
              <tr>
                  <td> </td>
                  <td> </td>
              </tr>
              <tr>
                <td class="data"><b>Tempat/Tanggal Lahir</b></td>
                <td><?php echo $model->tempat_lahir . ', ' . $model->tanggal_lahir; ?></td>
              </tr>
              <tr>
                <td class="data"><b>No. Handphone</b></td>
                <td><?php echo $model->no_handphone; ?></td>
              </tr>
              <tr>
                <td class="data"><b>Alamat</b></td>
                <td><?php echo $model->alamat; ?></td>
              </tr>
            </table>
        </div>
        <div class="two">
            <?php
                    $rows = (new \yii\db\Query())
                    ->select(['id','nama', 'tanggal_mulai','tanggal_selesai','lokasi', 'deskripsi', 'gambar_1','gambar_2','gambar_3','gambar_4','gambar_5'])
                    ->from('event')
                    ->limit(3)
                    ->orderBy(['id'=>SORT_DESC])
                    ->all();
                    foreach ($rows as $row){
                        echo "<div class='grid-sidebar'>";
                        echo Html::img(Yii::$app->request->BaseUrl.'/images/' . $row['gambar_1'], ['class'=>'foto-icon']);
                        echo Html::a($row['nama'], ['event/view','id'=>$row['id']], ['title' => 'View']);
                        echo "</div>";
                    }
                ?>
        </div>
    </div>
</div>