backend/models/Anggota.php
<?php

namespace backend\models;

use Yii;
use yii\web\UploadedFile;
use yii\helpers\Html;

/**
 * This is the model class for table "anggota".
 *
 * @property int $id
 * @property string $nama
 * @property string $tempat_lahir
 * @property string $tanggal_lahir
 * @property string $jenis_kelamin
 * @property string $jenis_suara
 * @property int $angkatan
 * @property string $jabatan
 * @property string $alamat_tetap
 * @property string $alamat_domisili
 * @property string $no_handphone
 * @property string $email
 * @property string $whatsapp
 * @property string $pekerjaan
 * @property string $line_id
 * @property string $gambar
 */
class Anggota extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'anggota';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['tanggal_lahir'], 'safe'],
            [['jenis_kelamin', 'jenis_suara', 'alamat_tetap', 'alamat_domisili'], 'string'],
            [['angkatan'], 'integer'],
            [['nama', 'tempat_lahir', 'jabatan', 'no_handphone', 'email', 'whatsapp', 'pekerjaan', 'line_id'], 'string', 'max' => 100],
            [['gambar'], 'file', 'skipOnEmpty' => true, 'extensions'=>'jpg, gif, png, jpeg'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nama' => 'Nama',
            'tempat_lahir' => 'Tempat Lahir',
            'tanggal_lahir' => 'Tanggal Lahir',
            'jenis_kelamin' => 'Jenis Kelamin',
            'jenis_suara' => 'Jenis Suara',
            'angkatan' => 'Angkatan',
            'jabatan' => 'Jabatan',
            'alamat_tetap' => 'Alamat Tetap',
            'alamat_domisili' => 'Alamat Domisili',
            'no_handphone' => 'No Handphone',
            'email' => 'Email',
            'whatsapp' => 'Whatsapp',
            'pekerjaan' => 'Pekerjaan',
            'line_id' => 'Line ID',
            'gambar' => 'Gambar',
        ];
    }

    public function afterSave($insert, $changedAttributes)
    {
        if(isset($this->gambar)){
            $this->gambar=UploadedFile::getInstance($this,'gambar');
            if(is_object($this->gambar)){
                $path=Yii::$app->basePath . '/web/images/members/';  //set directory path to save image
                $this->gambar->saveAs($path.$this->gambar);   //saving img in folder
                $this->gambar = 'members/'.$this->gambar;    //appending id to image name            
                \Yii::$app->db->createCommand()
                      ->update('anggota', ['gambar' => $this->gambar], 'id = "'.$this->id.'"')
                      ->execute(); //manually update image name to db
            }
        }
    }
}

backend/controllers/AnggotaController.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\Anggota;
use backend\models\AnggotaSearch;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\data\Pagination;
use yii\web\UploadedFile;
use yii\db\Query;

/**
 * AnggotaController implements the CRUD actions for Anggota model.
 */
class AnggotaController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['error', 'index', 'view'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['create', 'update', 'delete'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Anggota models.
     * @return mixed
     */
    public function actionIndex($angkatan=1)
    {
        // $query = Anggota::find()->where(['angkatan' => 2009]);
        // $countQuery = clone $query;
        // $pages = new Pagination(['totalCount' => $countQuery->count()]);
        // $models = $query->offset($pages->offset)
        //     ->limit($pages->limit)
        //     ->all();

        $myCondition = Yii::$app->user->isGuest;

        // $query = new Query;             
        // $query->select('angkatan')->from(TabAccount::anggota())->distinct();

        // $command = $query->createCommand();
        // $datas = $command->queryAll();

        // foreach ($datas as $data){

        // }

        $query = Yii::$app->db->CreateCommand('SELECT DISTINCT angkatan FROM anggota ORDER BY angkatan ASC')->queryAll();

        // $query = mysql_query("SELECT * FROM anggota WHERE angkatan=$angkatan");
        // while($row = mysql_fetch_array($query))
        // {

        // }

        $searchModel = new AnggotaSearch();
        $searchModel->angkatan = $angkatan;
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'myCondition' => $myCondition,
            'query' => $query,
            // 'models' => $models,
            // 'pages' => $pages,
        ]);
    }

    /**
     * Displays a single Anggota model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Anggota model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Anggota();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Anggota model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        // $model = $this->findModel($id);

        // if ($model->load(Yii::$app->request->post()) && $model->save()) {
        //     return $this->redirect(['view', 'id' => $model->id]);
        // }

        // $model->gambar = Yii::$app->basePath . '/web/images/members/' . $model->gambar;
        // return $this->render('update', [
        //     'model' => $model,
        // ]);


        $model = $this->findModel($id);
        $oldImage = $model->gambar;
        if ($model->load(Yii::$app->request->post()))
        {
            $image = UploadedFile::getInstance($model, 'gambar');
            if(!isset($image)){
                $model->gambar = $oldImage;
            }
            if($model->save())
            {
                if(isset($image)){
                    $image->saveAs(Yii::$app->basePath . '/web/images/members/' . $model->gambar);   
                }
            }
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Anggota model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Anggota model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Anggota the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Anggota::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

backend/controllers/EventController.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\Event;
use backend\models\EventSearch;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use yii\data\ActiveDataProvider;
/**
 * EventController implements the CRUD actions for Event model.
 */
class EventController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['error', 'index', 'view'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['create', 'update', 'delete'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Event models.
     * @return mixed
     */
    public function actionIndex()
    {
        $queryString = 'SELECT * FROM EVENT DESC';
        $dataProvider = new ActiveDataProvider([
            'query' => Event::find()->orderBy('id DESC'),
            'pagination' => [
                'pageSize' =>20,
            ],
        ]);

        $this->view->title = 'Event';
        return $this->render('index', ['dataProvider' => $dataProvider]);
    }

    /**
     * Lists all Event models.
     * @return mixed
     */
    public function actionIndex2()
    {
        $searchModel = new EventSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        $myCondition = Yii::$app->user->isGuest;

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'myCondition' => $myCondition,
        ]);
    }

    /**
     * Displays a single Event model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Event model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Event();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            // $image_1 = UploadedFile::getInstance($model, 'gambar_1');
            // $model->gambar_1= $image_1->name;
            // $path_1 = Yii::$app->basePath . '/web/images/events/' . $model->gambar_1;
            // if($model->save())
            // {
            //     $image_1->saveAs($path_1);
            //     // Yii::$app->getSession()->setFlash('error', 'User type inserted successfully');
            // }
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Event model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        // $model = $this->findModel($id);

        // if ($model->load(Yii::$app->request->post()) && $model->save()) {
        //     // $image_1 = UploadedFile::getInstance($model, 'gambar_1');
        //     // $model->gambar_1= $image_1->name;
        //     // $path_1 = Yii::$app->basePath . '/web/images/events/' . $model->gambar_1;
        //     // if($model->save())
        //     // {
        //     //     $image_1->saveAs($path_1);
        //     //     // Yii::$app->getSession()->setFlash('error', 'User type inserted successfully');
        //     // }
        //     return $this->redirect(['view', 'id' => $model->id]);
        // }

        // return $this->render('update', [
        //     'model' => $model,
        // ]);


        $model = $this->findModel($id);
        $oldImage_1 = $model->gambar_1;
        $oldImage_2 = $model->gambar_2;
        $oldImage_3 = $model->gambar_3;
        $oldImage_4 = $model->gambar_4;
        $oldImage_5 = $model->gambar_5;
        if ($model->load(Yii::$app->request->post()))
        {
            $image_1 = UploadedFile::getInstance($model, 'gambar_1');
            $image_2 = UploadedFile::getInstance($model, 'gambar_2');
            $image_3 = UploadedFile::getInstance($model, 'gambar_3');
            $image_4 = UploadedFile::getInstance($model, 'gambar_4');
            $image_5 = UploadedFile::getInstance($model, 'gambar_5');
            if(!isset($image_1)){
                $model->gambar_1 = $oldImage_1;
            }
            if(!isset($image_2)){
                $model->gambar_2 = $oldImage_2;
            }
            if(!isset($image_3)){
                $model->gambar_3 = $oldImage_3;
            }
            if(!isset($image_4)){
                $model->gambar_4 = $oldImage_4;
            }
            if(!isset($image_5)){
                $model->gambar_5 = $oldImage_5;
            }
            if($model->save())
            {
                if(isset($image_1)){
                    $image_1->saveAs(Yii::$app->basePath . '/web/images/members/' . $model->gambar_1);   
                }
                if(isset($image_2)){
                    $image_2->saveAs(Yii::$app->basePath . '/web/images/members/' . $model->gambar_2);   
                }
                if(isset($image_3)){
                    $image_3->saveAs(Yii::$app->basePath . '/web/images/members/' . $model->gambar_3);   
                }
                if(isset($image_4)){
                    $image_4->saveAs(Yii::$app->basePath . '/web/images/members/' . $model->gambar_4);   
                }
                if(isset($image_5)){
                    $image_5->saveAs(Yii::$app->basePath . '/web/images/members/' . $model->gambar_5);   
                }
            }
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Event model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Event model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Event the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Event::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

backend/views/anggota/_form.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\jui\DatePicker;
use kartik\file\FileInput;

/* @var $this yii\web\View */
/* @var $model backend\models\Anggota */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="anggota-form">

    <?php $form = ActiveForm::begin([
        'layout' => 'horizontal',
        'options'=>['enctype'=>'multipart/form-data'],
        'fieldConfig' => [
            'template' => "{label}\n{beginWrapper}\n{input}\n{hint}\n{error}\n{endWrapper}",
            'horizontalCssClasses' => [
                'label' => 'col-sm-2',
                'offset' => 'col-sm-offset-4',
                'wrapper' => 'col-sm-4',
                'error' => '',
                'hint' => '',
            ],
        ],
    ]); ?>

    <?= $form->field($model, 'nama')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'tempat_lahir')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'tanggal_lahir')->widget(DatePicker::className(),[
            'clientOptions' => [
                'defaultDate' => '2014-01-01',
                // 'yearRange' => 'c-50:c-20',
                'changeMonth'=> true,
                'changeYear'=> true,
            ],
            'options'=>['style'=>'width:250px;', 'class'=>'form-control'],
            'dateFormat' => 'yyyy-MM-dd',
        ]) ?>

    <?= $form->field($model, 'jenis_kelamin')->dropDownList([ 'Perempuan' => 'Perempuan', 'Laki-laki' => 'Laki-laki', ]) ?>

    <?= $form->field($model, 'jenis_suara')->dropDownList([ 'Sopran' => 'Sopran', 'Alto' => 'Alto', 'Tenor' => 'Tenor', 'Bass' => 'Bass', ]) ?>

    <?= $form->field($model, 'angkatan')->textInput() ?>

    <?= $form->field($model, 'jabatan')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'alamat_tetap')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'alamat_domisili')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'no_handphone')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'whatsapp')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'pekerjaan')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'line_id')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'gambar')->widget(FileInput::classname(), [
        'options' => ['accept' => 'image/*', 'multiple' => false],
        'pluginOptions' => [
            'showUpload' => false,
            'browseIcon' => '<i class="glyphicon glyphicon-camera"/> ',
        ]
    ]) ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/anggota/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\AnggotaSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="anggota-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'nama') ?>

    <?= $form->field($model, 'tempat_lahir') ?>

    <?= $form->field($model, 'tanggal_lahir') ?>

    <?= $form->field($model, 'jenis_kelamin') ?>

    <?php // echo $form->field($model, 'jenis_suara') ?>

    <?php // echo $form->field($model, 'angkatan') ?>

    <?php // echo $form->field($model, 'jabatan') ?>

    <?php // echo $form->field($model, 'alamat_tetap') ?>

    <?php // echo $form->field($model, 'alamat_domisili') ?>

    <?php // echo $form->field($model, 'no_handphone') ?>

    <?php // echo $form->field($model, 'email') ?>

    <?php // echo $form->field($model, 'whatsapp') ?>

    <?php // echo $form->field($model, 'pekerjaan') ?>

    <?php // echo $form->field($model, 'line_id') ?>

    <?php // echo $form->field($model, 'gambar') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/anggota/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Anggota */

$this->title = 'Create Anggota';
$this->params['breadcrumbs'][] = ['label' => 'Anggota', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="anggota-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/anggota/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\LinkPager;
use yii\widgets\ListView;
use yii\helpers\ArrayHelper;


/* @var $this yii\web\View */
/* @var $searchModel app\models\AnggotaSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Anggota';
?>

<div class="container3">
    <div class="anggota-index">
        <div class="sejarah-img">
            <?php echo Html::img(Yii::$app->request->BaseUrl.'/images/anggota.jpg', ['class'=>'imgSejarah']) ?>
        </div>
    
        <h1><?= Html::encode($this->title) ?></h1>
        <?php // echo $this->render('_search', ['model' => $searchModel]); ?>
    
        <p>
            <?php if (Yii::$app->user->isGuest == false) {
                    echo Html::a('Create Anggota', ['create'], ['class' => 'btn btn-success']);
                }
            ?>
        </p>
        <div class="one" >
            <div class="dataAnggota">
                <table class="table_negative table-striped" style="margin-bottom: 50px;">
                </table>
            </div>
            <?php
            $rows = (new \yii\db\Query())
                        ->select(['id','angkatan','nama', 'jenis_suara'])
                        ->from('anggota')
                        ->orderBy(['angkatan'=>SORT_ASC])
                        ->all();
            
            ?>
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-footable/3.1.6/footable.bootstrap.min.css" type="text/css" >
            <script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-footable/3.1.6/footable.min.js"></script>
            
            <script>
            var data = [];
            
            function dataAnggota(){
                <?php foreach($rows as $row) { ?>  
                        data.push({ colom1 : ' <?php echo Html::a($row['angkatan'], ['angkatan/view','id'=>$row['id']]) ?>', colom2 : '<?php echo Html::a($row['jenis_suara'], ['anggota/view','id'=>$row['id']]) ?>', colom3 : '<?php echo Html::a($row['nama'], ['anggota/view','id'=>$row['id']]) ?>' });
                
                <?php } ?>
                return data;
            }
            
            jQuery(function($){
                $('.table_negative').footable({
                    "paging": {
                        "enabled": true,
                        "size" : 10
                    },
                    "filtering": {
                        "enabled": true
                    },
                    "sorting": {
                        "enabled": true
                    },
                    "columns": [{"name": "colom1", "title" :"Angkatan"}, {"name": "colom2", "title" :"Jenis Suara"}, {"name": "colom3", "title" :"Nama"}],
                    "rows":   dataAnggota()
                              
                });
            });
        </script>
        </div>
        <div class="two">
            <?php
                    $rows = (new \yii\db\Query())
                    ->select(['id','nama', 'tanggal_mulai','tanggal_selesai','lokasi', 'deskripsi', 'gambar_1','gambar_2','gambar_3','gambar_4','gambar_5'])
                    ->from('event')
                    ->limit(3)
                    ->orderBy(['id'=>SORT_DESC])
                    ->all();
                    foreach ($rows as $row){
                        echo "<div class='grid-sidebar'>";
                        echo Html::img(Yii::$app->request->BaseUrl.'/images/' . $row['gambar_1'], ['class'=>'foto-icon']);
                        echo Html::a($row['nama'], ['event/view','id'=>$row['id']], ['title' => 'View']);
                        echo "</div>";
                    }
                ?>
        </div>
        <?php /* ListView::widget([
            'options' => [
                'tag' => 'div',
            ],
            'dataProvider' => $dataProvider,
            'itemView' => function ($model, $key, $index, $widget) {
                return '<div>' . $model->angkatan . '</div>';
            },
            'itemOptions' => [
                'tag' => false,
            ],
            'summary' => '',
            'layout' => '{items} {pager}',
            
            'pager' => [
                // Use custom pager widget class
                'class' => backend\widgets\pager\Pager::className(),
                
                // Configurations for default LinkPager widget are still available
                'firstPageLabel' => 'First',
                'lastPageLabel' => 'Last',
                'maxButtonCount' => 4,
                            // Options for <ul> wrapper of default pager buttons are still available
                'options' => [
                    'class' => 'pagination',
                    'style' => 'display:inline-block;float:left;margin:20px 10px 20px 0;width:auto;'
                ],
                // Style for page size select
                'sizeListHtmlOptions' => [
                    'class' => 'form-control',
                    'style' => 'display:inline-block;float:left;margin:20px 10px 20px 0;width:auto;'
                ],
                // Style for go to page input
                'goToPageHtmlOptions' => [
                    'class' => 'form-control',
                    'style' => 'display:inline-block;float:left;margin:20px 10px 20px 0;width:auto;'
                ],
            ],
    
        ]);
        */?>
    
        <?php 
            // foreach ($models as $model) {
            //     // display $model here
            //     echo $model->nama;
            // }
    
            // echo LinkPager::widget([
            //     'pagination' => $pages,
            // ]);
    
        ?>
    
    </div>
</div>

backend/views/anggota/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Anggota */

$this->title = 'Update Anggota';
$this->params['breadcrumbs'][] = ['label' => 'Anggota', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="anggota-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/anggota/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model backend\models\Anggota */

$this->title = $model->id;
?>
<div class="container3">
    <div class="anggota-view">
        <div class="sejarah-img">
            <?php echo Html::img(Yii::$app->request->BaseUrl.'/images/anggota.jpg', ['class'=>'imgSejarah']) ?>
        </div>

    
        <p>
            <?php if (Yii::$app->user->isGuest == false) {
                    echo Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']);
                }
            ?>
            <?php if (Yii::$app->user->isGuest == false) {
                    echo Html::a('Delete', ['delete', 'id' => $model->id], [
                        'class' => 'btn btn-danger',
                        'data' => [
                            'confirm' => 'Are you sure you want to delete this item?',
                            'method' => 'post',
                        ],
                    ]);
                }
            ?>
        </p>
        <div class="one">
                    <?php echo Html::img(Yii::$app->request->BaseUrl.'/images/' . $model->gambar, ['class'=>'foto-profil-detail']) ?>

        <h1><?= Html::encode($model->nama) ?></h1>
            <div class="detailAnggota">
            <?= DetailView::widget([
                'model' => $model,
                'attributes' => [
                    // 'id',
                //    'nama',
                    'tempat_lahir',
                    'tanggal_lahir',
                    'jenis_kelamin',
                    'jenis_suara',
                    'angkatan',
                    'jabatan',
                    'alamat_tetap',
                    'alamat_domisili',
                    'no_handphone',
                    'email:email',
                    'whatsapp',
                    'pekerjaan',
                    'line_id',
                ],
            ]) ?>
            </div>
        </div>
        <div class="two">
                <?php
                        $rows = (new \yii\db\Query())
                        ->select(['id','nama', 'tanggal_mulai','tanggal_selesai','lokasi', 'deskripsi', 'gambar_1','gambar_2','gambar_3','gambar_4','gambar_5'])
                        ->from('event')
                        ->limit(3)
                        ->orderBy(['id'=>SORT_DESC])
                        ->all();
                        foreach ($rows as $row){
                            echo "<div class='grid-sidebar'>";
                            echo Html::img(Yii::$app->request->BaseUrl.'/images/' . $row['gambar_1'], ['class'=>'foto-icon']);
                            echo Html::a($row['nama'], ['event/view','id'=>$row['id']], ['title' => 'View']);
                            echo "</div>";
                        }
                    ?>
        </div>
    </div>
</div>